### ISSUE TITLE
Fetching just text. Not Photos, TOC or Tables.

### ISSUE THREAD

**Issue by berkdurmus** [Raureif/WikipediaKit#12]
Hi! Firstly, thank you for open sourcing this great project. When I try to request an article, it fetches all the data on the page as expected. How can I filter out Photos, TOC, Tables  and links? I want to fetch just the text inside sections just like requestArticleSummary method does. I just tried to adjust the fragment parameter but I could not achieve it. I used requestArticleSummary but the fetched text is too short and I want to get text data of other sections.

**Comment by frankrausch** [comment]
Hi Berk,

I am not sure that you can get exactly what you want with only the Wikipedia API. Have you checked the docs here?
https://www.mediawiki.org/wiki/API:Main_page

In my experience, retrieving everything first and then stripping out whatever you don’t need (via the DOM/regex, etc.) is the way to go. :)

Let me know if you find out anything. Thanks.
