### ISSUE TITLE
Non-optimized search API is unavailable

### ISSUE THREAD

**Issue by yujinakayama** [Raureif/WikipediaKit#17]
The README mentions `WikipediaSearchMethod` for switching `.prefix` or `.fullText` search.
However the method [`requestSearchResults`](https://github.com/Raureif/WikipediaKit/blob/1c9d449aab9cf47f058a834caf4ff630fa283e04/Sources/Wikipedia%2BSearch.swift#L82-L90), which takes `WikipediaSearchMethod` as a parameter, is not marked as `public` so it's not available from the framework users.
Am I missing something?

**Comment by frankrausch** [comment]
Thanks for making me aware of this issue. I have marked the method as public [and released a new version](https://github.com/Raureif/WikipediaKit/releases/tag/v3.0.3).

**Comment by yujinakayama** [comment]
Thank you for the quick action!
