### ISSUE TITLE
Version tags are not compatible with Swift Playgrounds for iPad

### ISSUE THREAD

**Issue by fcanas** [Raureif/WikipediaKit#19]
Version tags prefixed with "v" are not compatible with Swift Playgrounds for iPad.

See [this issue](https://forums.swift.org/t/support-for-v-prefixed-version-tags-in-spm-swift-playgrounds-for-ipad/54845) on the Swift Forums.

This repository mostly prefixes tags with "v", except for version 2.0.7. So when adding this package as a dependency, things mostly appear to work. But loading an article fails due to changes in the WikiMedia APIs. 

I don't think that the full version history should be revised to remove the "v", but perhaps new tags could omit it?

**Comment by frankrausch** [comment]
Ah, thanks. I didn’t know that. Will consider this in the future.

**Comment by frankrausch** [comment]
Does this release fix the issue, @fcanas?
https://github.com/Raureif/WikipediaKit/releases/tag/3.0.4
