### ISSUE TITLE
Incompatible with Swift 5.6.1 compiler

### ISSUE THREAD

**Issue by bjoern2000** [Raureif/WikipediaKit#20]
When importing WikipediaKit I get this error: `Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.6.1 compiler`

I'm using Xcode 13.4.1

![Screen Shot 2022-07-30 at 9 28 12 AM](https://user-images.githubusercontent.com/7944323/181926367-58f4806f-e83d-44cc-8bf3-771b88b52127.png)

**Comment by frankrausch** [comment]
Please try cleaning your build and/or deleting the corresponding folder in `Derived Data`.

**Comment by bjoern2000** [comment]
Thanks for the suggestion! I tried both and also setting Build Options > Build Libraries for Distribution to Yes, but am still getting the same compiler error :(

**Comment by frankrausch** [comment]
Try restarting your computer.
If that doesn’t help, remove and re-add the package.

This is very likely an issue on your computer because this repository does not come with any precompiled modules.

**Comment by bjoern2000** [comment]
I used Carthage previously, removed that and re-added the package via Swift Package Manager, that did the trick. Thank you for your help! 

Now I need to resolve issues with other dependencies. Always fun updating an app you hadn't touched in 2 years...

**Comment by frankrausch** [comment]
Haha, yes. I feel your pain. 🙌
