### ISSUE TITLE
What happened to V for Wiki?

### ISSUE THREAD

**Issue by InvaderJ** [Raureif/WikipediaKit#24]
App nonfunctional and is delisted from the Store, sites are gone, etc. :( What’s the scoop?

**Comment by Sneezelax** [comment]
Wondering the same

**Comment by InvaderJ** [comment]
Someone on Reddit pointed me to this: https://mastodon.social/@frankrausch/110685535104186172 

HUGE bummer. Apparently the app itself had been discontinued for a while, then API change broke article retrieval. Super crushed. V for Wiki has been on my iPhone's home screen _forever._ T_T

**Comment by Sneezelax** [comment]
Ahhh that's so sad. Thanks for the info though.. it's good to have the closure at least. I guess it joins Apollo in my app graveyard this month

**Comment by InvaderJ** [comment]
_Tell me about it._ Both on my home screen. -____- Such a sad week!

**Comment by frankrausch** [comment]
Thanks for the kind words about V for Wiki. Yes, we discontinued the app a while ago.

I had hoped that it would remain functional for a long time, but Wikipedia pulled the plug on the Mobile Content Service. More details here:
https://github.com/Raureif/WikipediaKit/issues/25
