### ISSUE TITLE
Carthage installation

### ISSUE THREAD

**Issue by AdrianBinDC** [Raureif/WikipediaKit#4]
I'm attempting to install via Carthage. Here's my Cartfile:

`github "Raureif/WikipediaKit" ~> 1.0.0-beta.5`

also tried with:

`github "Raureif/WikipediaKit"  "master"`

When I type `carthage update` in console, I get the following error:

> *** Fetching WikipediaKit
> *** Checking out WikipediaKit at "v1.0.0-beta.5"
> *** xcodebuild output can be found in /var/folders/d0/zncpdgsn2l141snb7hr0m_xh0000gn/T/carthage-xcodebuild.2cz4UH.log
> *** Skipped building WikipediaKit due to the error:
> Dependency "WikipediaKit" has no shared framework schemes

**Comment by frankrausch** [comment]
Thanks. I’ll have a look at this. 

Until I get this fixed, you can install it manually:

Add a git submodule, drag the WikipediaKit project into your own project/workspace, then add the WikipediaKit framework in your build settings.

**Comment by jessecanderson** [comment]
I ran into this same problem. I opened up the Xcode project and under Product -> Scheme -> Manage Schemes... I found that the schemes were not shared. I checked the boxes and that fixed my Carthage build issues.

**Comment by frankrausch** [comment]
Thanks @jessecanderson! I have shared the schemes and pushed to `master`. Hope this fixes the issue for you as well, @AdrianBinDC.

**Comment by frankrausch** [comment]
Closing the issue. If you still see this issue, please feel free to reopen. Thanks.
