### ISSUE TITLE
displayText in articlePreviews is empty

### ISSUE THREAD

**Issue by bjoern2000** [Raureif/WikipediaKit#6]
First of all, thanks a million for this great library! I am building WikiTrip, an app that reads out article summaries around you, for road trips or city walks. I am a total programming newb.

I am using requestNearbyResults, select a random result in the array, render displayTitle into the UI and  send displayText to AVSpeechSynthesizer. Couple of days ago, displayText started to have no content. Is this a known issue with the API, or an issue on my side?

As a workaround, I am fetching displayText via another call using requestOptimizedSearchResults, but that seems unnecessary to me.

**Comment by frankrausch** [comment]
Hi @bjoern2000,

glad you like WikipediaKit! 🙌

By default, the article extracts are not loaded, you have to pass `loadExtracts: true` in `requestNearbyResults`. Do you have that?

**Comment by frankrausch** [comment]
Cool. 

There’s no further documentation, but looking at the code is always a good idea. ;)

https://github.com/Raureif/WikipediaKit/blob/master/Sources/Wikipedia%2BNearbySearch.swift#L34-L43

**Comment by bjoern2000** [comment]
Ah, got it. Thanks a lot. I'm a newb, so this is the first library I am using.

**Comment by frankrausch** [comment]
Great! Keep it up. I will buy your app when it’s on the App Store as a motivation to keep going. 😸
So please do notify me when it’s available.
