### ISSUE TITLE
Where can I find the example of Wikipedia Article?

### ISSUE THREAD

**Issue by danielsGit** [Raureif/WikipediaKit#8]
Actually I am trying to render the wikipedia article on WkWebView.
But it doesn't looks good. Images are not full width and text size are very small...
I would be appreciate if anybody can share the rendering example of wikipedia article.

**Comment by frankrausch** [comment]
The API always gives you unstyled HTML (except for the inline styles that are unfortunately mingled in the markup).

Have a look at the [stylesheet in the official Wikipedia iOS app](https://github.com/wikimedia/wikipedia-ios/tree/ca4df05eaeab29aaa9c023aa8bb9ce59f5feb39e/Wikipedia/assets).

**Comment by danielsGit** [comment]
Ok thanks for your fast reply. I will take a look
